language: go
sudo: false
notifications:
  email: false
jobs:
  include:
    - stage: test
      go_import_path: github.com/home-IoT/jupiter
      install:
        - make get-tools
      os: linux
      go: 1.9.x
      script:
        - make go-dep go-validate
addons:
  ssh_known_hosts: github.com