// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetSensorsListHandlerFunc turns a function with the right signature into a get sensors list handler
type GetSensorsListHandlerFunc func(GetSensorsListParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetSensorsListHandlerFunc) Handle(params GetSensorsListParams) middleware.Responder {
	return fn(params)
}

// GetSensorsListHandler interface for that can handle valid get sensors list params
type GetSensorsListHandler interface {
	Handle(GetSensorsListParams) middleware.Responder
}

// NewGetSensorsList creates a new http.Handler for the get sensors list operation
func NewGetSensorsList(ctx *middleware.Context, handler GetSensorsListHandler) *GetSensorsList {
	return &GetSensorsList{Context: ctx, Handler: handler}
}

/*GetSensorsList swagger:route GET /sensors getSensorsList

Returns the list of sensors

*/
type GetSensorsList struct {
	Context *middleware.Context
	Handler GetSensorsListHandler
}

func (o *GetSensorsList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetSensorsListParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
