// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSensorDataParams creates a new GetSensorDataParams object
// with the default values initialized.
func NewGetSensorDataParams() GetSensorDataParams {
	var ()
	return GetSensorDataParams{}
}

// GetSensorDataParams contains all the bound params for the get sensor data operation
// typically these are obtained from a http.Request
//
// swagger:parameters getSensorData
type GetSensorDataParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	SensorID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *GetSensorDataParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	rSensorID, rhkSensorID, _ := route.Params.GetOK("sensorId")
	if err := o.bindSensorID(rSensorID, rhkSensorID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetSensorDataParams) bindSensorID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.SensorID = raw

	return nil
}
