// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetSensorDataRawHandlerFunc turns a function with the right signature into a get sensor data raw handler
type GetSensorDataRawHandlerFunc func(GetSensorDataRawParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetSensorDataRawHandlerFunc) Handle(params GetSensorDataRawParams) middleware.Responder {
	return fn(params)
}

// GetSensorDataRawHandler interface for that can handle valid get sensor data raw params
type GetSensorDataRawHandler interface {
	Handle(GetSensorDataRawParams) middleware.Responder
}

// NewGetSensorDataRaw creates a new http.Handler for the get sensor data raw operation
func NewGetSensorDataRaw(ctx *middleware.Context, handler GetSensorDataRawHandler) *GetSensorDataRaw {
	return &GetSensorDataRaw{Context: ctx, Handler: handler}
}

/*GetSensorDataRaw swagger:route GET /sensors/{sensorId}/raw getSensorDataRaw

Returns the data of a particular sensor in simple JSON

*/
type GetSensorDataRaw struct {
	Context *middleware.Context
	Handler GetSensorDataRawHandler
}

func (o *GetSensorDataRaw) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetSensorDataRawParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
