#!/usr/bin/env bash
#
# Extracts the MANIFEST file(s) from a service REPO
#
# Usage: get-manifest [repo_dir]
#
# Copyright (c) 2016-2018 Roozbeh Farahbod
# Distributed under the MIT License.
#

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
SCRIPT_NAME="get-manifest"

source ${SCRIPT_DIR}/common

REPO_DIR=$("${SCRIPT_DIR}/check-repo-dir" "$1")
CHECK_DIR="$?"
if [ "$CHECK_DIR" != "0" ]
then
  showUsage ${BASH_SOURCE[0]}
  exit 1
fi

MAN_FILE=${REPO_DIR}/MANIFEST

if [ ! -e "${MAN_FILE}" ]
then
  printError "No MANIFEST file could be found."
  exit 1
fi

printf '%s\n' "${MAN_FILE}"
exit 0
